import type {
  Profile,
  Project,
  VacationRequest,
  ProjectAssignment,
  ProjectLike,
  Notification,
  ExperienceEntry,
} from './types'

function c(
  id: string,
  name: string,
  role_title: string,
  seniority: Profile['seniority'],
  skills: string[],
  available_from: string | null,
  practice_area: string | null = null,
  internship_end_date: string | null = null,
  cv: { bio?: string; education?: string; languages?: string; years_of_experience?: number; certifications?: string[]; experience?: ExperienceEntry[] } = {},
): Profile {
  return {
    id, name, role_title, seniority, practice_area, skills,
    available_from,
    internship_start_date: null, internship_end_date,
    user_role: 'consultant', is_active: true, created_at: '2025-01-01T00:00:00Z',
    bio: cv.bio ?? null,
    education: cv.education ?? null,
    languages: cv.languages ?? null,
    years_of_experience: cv.years_of_experience ?? null,
    certifications: cv.certifications ?? [],
    experience: cv.experience ?? [],
  }
}

export const mockConsultants: Profile[] = [
  // Senior Partners
  c('c1', 'Hernando Baquero', 'Senior Partner', 'Senior Partner',
    ['Digital Transformation', 'Operational Excellence', 'IT Strategy', 'Strategic Planning', 'Business Intelligence', 'Post-merger Integration'],
    '2026-12-31', null, null, {
      bio: 'Hernando tiene más de 20 años de experiencia en transformación digital, excelencia operativa, planificación estratégica de negocios y TI y gestión de proyectos complejos. Antes de fundar Advantis en 2003, fue consultor en Booz Allen Hamilton y Gerente de una empresa de consultoría colombiana.',
      education: 'Ingeniero Industrial, Universidad de los Andes · MBA, INSEAD',
      languages: 'Español, Inglés',
      years_of_experience: 20,
      experience: [
        { id: 'e1a', title: 'Transformación Digital y Tecnologías de la Información', client: 'Sector Financiero, LATAM', period: '2003 – presente', description: 'Soporte en Transformación Digital — mejora de la experiencia del cliente, modernización de aplicaciones heredadas y excelencia operativa. Definición de visión y hoja de ruta de TI para más de 100 empresas de diversas industrias. Due Diligence de TI para empresas tecnológicas, bancos y fondos de pensiones.' },
        { id: 'e1b', title: 'Transformación Organizacional', client: 'Banca y Sector Real', period: '2003 – presente', description: 'Integración post-fusión de bancos, fondos de pensiones y empresas de consumo con énfasis en TI. Evaluación y diseño de esquemas de servicios compartidos. Rediseño y mejora de la eficacia operativa.' },
        { id: 'e1c', title: 'Excelencia Operativa y Organizacional', client: 'Múltiples industrias', period: '2003 – presente', description: 'Evaluación de capacidades operativas, diseño y transformación del modelo operativo y tecnológico. Implantación de estrategias y sistemas de inteligencia de negocios.' },
        { id: 'e1d', title: 'Consultor, Práctica de TI', client: 'Booz Allen Hamilton', period: '1998 – 2003', description: 'Proyectos de TI para clientes en múltiples industrias en Colombia y América Latina.' },
      ],
    }),
  // Partners
  c('c2', 'John Jairo Romero', 'Partner', 'Partner',
    ['Digital Transformation', 'IT Strategy', 'Cybersecurity', 'M&A', 'Financial Services', 'Process Improvement'],
    '2026-12-31', 'IT / Digital', null, {
      bio: 'John Jairo ha dedicado su carrera de más de 27 años en consultoría a ayudar a empresas en múltiples industrias a transformar su negocio mediante tecnología e innovación digital.',
      education: 'Ingeniero de Sistemas, Universidad de Los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 27,
    }),
  c('c3', 'Juan Fernando Forero', 'Partner', 'Partner',
    ['IT Planning', 'IT Management', 'Systems Architecture', 'Project Management', 'Software Selection', 'Integration'],
    '2026-08-21', 'Strategy & Technology', null, {
      bio: 'Juan Fernando cuenta con más de 30 años de experiencia en consultoría gerencial para resolver asuntos estratégicos de TI — planeación y gestión de TI, arquitectura, selección de soluciones y dirección de proyectos de implementación en América Latina.',
      education: 'Ingeniero de Sistemas y Computación, Universidad de Los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 30,
      experience: [
        { id: 'e3a', title: 'Planeación y Gestión de TI', client: 'Sector Financiero y Real, Norte de América Latina', period: '1994 – presente', description: 'Definición de estrategias de TI, evaluación de capacidades y diseño de modelos de gestión para grandes corporaciones. Más de 30 proyectos en Colombia, Panamá, Ecuador y Venezuela.' },
        { id: 'e3b', title: 'Arquitectura de TI y Selección de Soluciones', client: 'Banca, Seguros, Retail', period: '1994 – presente', description: 'Diseño de arquitecturas tecnológicas y evaluación de plataformas. Estructuración y dirección de procesos de selección de software ERP, CRM y core bancario.' },
        { id: 'e3c', title: 'Gerencia de Proyectos de Implementación', client: 'Múltiples clientes LATAM', period: '1994 – presente', description: 'Dirección de proyectos de implementación de soluciones tecnológicas complejas. Diseño y puesta en marcha de integraciones entre sistemas.' },
      ],
    }),
  // Director
  c('c4', 'Henry Jaimes', 'Director', 'Director',
    ['IT Strategy', 'IT Architecture', 'Digital Transformation', 'Organizational Design', 'Agile', 'Due Diligence'],
    '2026-11-30', null, null, {
      bio: 'Henry tiene una amplia experiencia en consultoría en estrategia de tecnología y negocios, arquitectura de TI, implementación de estrategias de transformación digital, diseño organizacional y metodologías ágiles.',
      education: 'Ingeniero de Sistemas, Universidad de Los Andes · Magíster en Tecnologías de la Información para el Negocio, Universidad de Los Andes',
      languages: 'Español, Inglés',
      certifications: ['Scrum Master Certificado'],
      experience: [
        { id: 'e4a', title: 'Estrategia de Negocios y de TI', client: 'Sector Financiero y Telecomunicaciones', period: '2010 – presente', description: 'Definición de estrategias de TI alineadas al negocio, evaluación de capacidades digitales y diseño de hojas de ruta de transformación.' },
        { id: 'e4b', title: 'Arquitectura de TI y Diseño Organizacional', client: 'Banca, Seguros, Gobierno', period: '2010 – presente', description: 'Diseño de arquitecturas empresariales, evaluación de plataformas tecnológicas y modelos de gestión de TI. Due diligence técnicos en procesos de fusiones y adquisiciones.' },
        { id: 'e4c', title: 'Transformación Digital y Metodologías Ágiles', client: 'Múltiples industrias', period: '2015 – presente', description: 'Liderazgo de programas de transformación digital y adopción de metodologías ágiles (Scrum, SAFe) en grandes organizaciones.' },
      ],
    }),
  // Senior Managers
  c('c5', 'Andrés Cubillos', 'Senior Manager', 'Senior Manager',
    ['Operational Excellence', 'IT Strategy', 'Enterprise Architecture', 'Agile', 'Software Implementation', 'Process Optimization'],
    '2026-05-29', null, null, {
      bio: 'Andrés tiene más de 12 años de experiencia enfocándose en dirección de proyectos complejos, planeación de TI, modelos de gestión y transformación de modelos operativos para diversas líneas de negocio.',
      education: 'Ingeniero, Universidad de Los Andes',
      years_of_experience: 12,
      experience: [
        { id: 'e5a', title: 'Excelencia Operacional y Transformación de Modelos Operativos', client: 'Sector Financiero y Salud', period: '2018 – presente', description: 'Transformación de modelos operativos para procesos financieros, atención al cliente, comercial y back office (shared services). Optimización de procesos con metodologías Lean y Six Sigma.' },
        { id: 'e5b', title: 'Estrategia de TI y Arquitectura Empresarial', client: 'Múltiples industrias', period: '2018 – presente', description: 'Planeación de TI, diseño de modelos de gestión y evaluación de capacidades digitales. Gestión ágil de proyectos de implementación de software.' },
        { id: 'e5c', title: 'Gerente y Consultor Senior', client: 'Ernst & Young', period: '2012 – 2018', description: 'Proyectos estratégicos, organizacionales y de tecnología en múltiples industrias.' },
      ],
    }),
  c('c6', 'Jaime Barco', 'Experto Datos y Analítica', 'Senior Manager',
    ['Data Analytics', 'Data Mining', 'Business Intelligence', 'AI/ML', 'Data Quality', 'Data Strategy'],
    '2026-12-31', null, null, {
      bio: 'Jaime ha participado en más de 80 proyectos relacionados con Data y Analítica. Especialista en técnicas de minería de datos, calidad de datos e implantación de sistemas de inteligencia artificial.',
      education: 'Ingeniero de Sistemas, Universidad Autónoma de Manizales · Especialización en Desarrollo Gerencial, Universidad Autónoma · PDD, INALDE',
      languages: 'Español, Portugués',
      years_of_experience: 20,
      experience: [
        { id: 'e6a', title: 'Estrategia y Gobierno de Datos', client: 'Sector Financiero y Retail, LATAM', period: '2004 – presente', description: 'Diseño e implantación de estrategias de calidad de datos, gobierno de datos y arquitecturas analíticas para más de 80 proyectos en Colombia, Brasil y América Latina.' },
        { id: 'e6b', title: 'Business Intelligence e Inteligencia Artificial', client: 'Banca, Seguros, Retail', period: '2004 – presente', description: 'Implantación de sistemas de BI y plataformas de IA. Minería de datos aplicada a riesgo crediticio, fraude, fidelización de clientes y optimización de operaciones.' },
        { id: 'e6c', title: 'Calidad de Datos y Master Data Management', client: 'Múltiples industrias', period: '2004 – presente', description: 'Diagnóstico, diseño e implementación de marcos de calidad de datos y MDM. Definición de roles, procesos y herramientas de gestión de datos maestros.' },
      ],
    }),
  c('c7', 'Carla Villaverde', 'Directora Talento Humano', 'Senior Manager',
    ['HR Strategy', 'Talent Acquisition', 'Organizational Design', 'Employer Branding', 'Engagement Strategy', 'Change Management'],
    '2026-07-31', null, null, {
      bio: 'Carla cuenta con más de 15 años de experiencia en talento humano, trabajando en la definición e implementación de estrategias que apalanquen los objetivos del negocio e incrementen los resultados de los equipos.',
      languages: 'Español, Inglés',
      years_of_experience: 15,
    }),
  c('c8', 'Felipe Estrada', 'Senior Manager', 'Senior Manager',
    ['Digital Transformation', 'IT Strategy', 'Data Strategy', 'IT Architecture', 'Business Strategy'],
    '2026-12-31', null, null, {
      bio: 'Felipe tiene 10+ años de experiencia. Anteriormente trabajó en IBM Colombia como consultor de TI y como líder de TI para aplicaciones y estrategias de mercadeo digital.',
      education: 'Ingeniero en Sistemas e Informática, Universidad de los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 10,
      certifications: ['Scrum Master Certificado'],
    }),
  c('c9', 'Iván Melo', 'Gerente Senior – Especialista Arquitectura TI', 'Senior Manager',
    ['IT Architecture', 'Enterprise Architecture', 'Digital Transformation', 'IT Strategy', 'Software Selection', 'Financial Services'],
    '2026-08-21', null, null, {
      bio: 'Iván Mauricio tiene 15+ años de experiencia en proyectos de arquitectura empresarial y asuntos estratégicos de TI, con amplia experiencia en transformación digital y selección de software en instituciones financieras en América Latina.',
      education: 'Máster en Ingeniería e Ingeniero de Sistemas y Computación, Universidad de Los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 15,
      experience: [
        { id: 'e9a', title: 'Arquitectura Empresarial y de TI', client: 'Instituciones Financieras, LATAM', period: '2010 – presente', description: 'Diseño de arquitecturas empresariales y tecnológicas para bancos, aseguradoras y fondos de pensiones en Colombia, Ecuador, Perú y México. Definición de hojas de ruta de evolución tecnológica.' },
        { id: 'e9b', title: 'Selección de Software y Transformación Digital', client: 'Sector Financiero y Real', period: '2010 – presente', description: 'Dirección de procesos de selección e implementación de soluciones core bancario, ERP y plataformas digitales. Evaluación de arquitecturas cloud y definición de estrategias de migración.' },
      ],
    }),
  // Managers
  c('c10', 'Magda Patiño', 'Especialista en Gestión de Proyectos', 'Manager',
    ['Project Management', 'Software Implementation', 'Change Management', 'QA', 'ERP'],
    '2026-08-21', 'Implementation', null, {
      bio: 'Magda es Especialista de Gestión de Proyectos con más de 25 años de experiencia en implementación de soluciones informáticas y estrategias de negocio para empresas públicas y privadas en múltiples sectores.',
      education: 'Ingeniera de Sistemas, Universidad de Los Andes',
      years_of_experience: 25,
      certifications: ['Scrum Master Certificada'],
    }),
  c('c11', 'Alejandro Manrique', 'Manager', 'Manager',
    ['Strategy', 'Business Analysis', 'Financial Modeling'],
    null),
  c('c12', 'John Casallas', 'Manager', 'Manager',
    ['Project Management', 'Software Implementation', 'IT Strategy', 'Enterprise Architecture', 'Digital Transformation', 'Business Process Automation'],
    '2026-11-30', null, null, {
      bio: 'John cuenta con 13+ años de experiencia. Sus principales áreas de especialización son gestión de proyectos de implementación de software, arquitectura empresarial y transformación digital.',
      education: 'Ingeniero de Sistemas, Universidad de Los Andes · Magíster en Ingeniería de Sistemas con énfasis en Arquitectura Empresarial, Universidad de Los Andes',
      years_of_experience: 13,
    }),
  c('c13', 'Felipe Mediorreal', 'Manager', 'Manager',
    ['Operations', 'Supply Chain', 'Process Optimization'],
    null),
  c('c14', 'Santiago Serna', 'Manager', 'Manager',
    ['Business Strategy', 'Digital Transformation', 'Operational Excellence', 'Agile Transformation'],
    '2026-12-31', null, null, {
      bio: 'Santiago Serna cuenta con más de 8 años de experiencia en proyectos de estrategia de negocios, transformación digital, gestión de tecnología y excelencia operacional.',
      education: 'MBA, Duke University · Ingeniero Industrial y Civil, Universidad de Los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 8,
    }),
  c('c15', 'Angélica Tarazona', 'Manager', 'Manager',
    ['HR', 'Finance', 'Organizational Design', 'Change Management', 'Talent Management'],
    '2026-08-21', null, null, {
      education: 'Magíster en Finanzas, Universidad de Los Andes · Administradora y Economista, Universidad Metropolitana (Caracas)',
    }),
  // Senior Associates
  c('c16', 'Andrea Rosales', 'Senior Associate', 'Senior Associate',
    ['Business Analysis', 'Process Optimization', 'Excel'],
    '2026-12-31'),
  c('c17', 'Guillermo Ferro', 'Asociado Senior', 'Senior Associate',
    ['IT Strategy', 'IT Architecture', 'Digital Transformation', 'Enterprise Architecture'],
    '2026-11-30', null, null, {
      education: 'Magíster en Arquitectura de TI, Universidad de los Andes',
    }),
  c('c18', 'Diego Castro', 'Asociado', 'Senior Associate',
    ['IT Strategy', 'Digital Transformation', 'Agile', 'Lean Digital', 'Organizational Strategy'],
    null, null, null, {
      bio: 'Diego Castro cuenta con 4 años de experiencia en proyectos de estrategia de tecnología y negocio, estrategia organizacional, implementación de metodologías ágiles y lean digital.',
      languages: 'Español, Inglés',
      years_of_experience: 4,
    }),
  c('c19', 'Raúl Aular', 'Asociado', 'Associate',
    ['IT Management', 'Strategic Planning', 'Process Management', 'ERP', 'Turnaround', 'Retail'],
    '2026-11-30', null, null, {
      bio: 'Raúl cuenta con experiencia en implementación de modelos de gestión de TI, rediseño e implementación de procesos y planes de turnaround en retailers de diferentes industrias.',
      languages: 'Español, Inglés, Portugués',
    }),
  c('c20', 'Lina Gutiérrez', 'Senior Associate', 'Senior Associate',
    ['Change Management', 'Training', 'Communications'],
    null),
  c('c21', 'Juan David Figueroa', 'Asociado Sr', 'Senior Associate',
    ['Business Strategy', 'Digital Transformation', 'Process Optimization', 'Operating Model Design', 'Financial Efficiency'],
    '2026-05-29', null, null, {
      bio: 'Juan David cuenta con más de 6 años de experiencia en estrategia de negocio y tecnología, transformación digital y optimización de procesos. Antes de BIP fue consultor en Accenture y Globant.',
      education: 'Economista, Pontificia Universidad Javeriana',
      languages: 'Español, Inglés',
      years_of_experience: 6,
    }),
  // Associates
  c('c22', 'Antonio Pérez', 'Asociado', 'Associate',
    ['Digital Transformation', 'ERP', 'CRM', 'IT Strategy', 'Energy', 'Carve-out'],
    '2026-12-31', null, null, {
      bio: 'Antonio tiene más de 6 años de experiencia en consultoría estratégica y de operaciones en los sectores de energía, utilities y servicios financieros.',
      languages: 'Español (nativo), Inglés C1',
      years_of_experience: 6,
    }),
  c('c23', 'Santiago Restrepo', 'Consultor Senior', 'Associate',
    ['Digital Transformation', 'Software Implementation', 'IT Strategy', 'Operational Excellence', 'Strategic Planning'],
    '2026-11-30', null, null, {
      bio: 'Santiago cuenta con 3 años de experiencia en proyectos de transformación digital, implementación de software, definición de estrategia de tecnología y excelencia operacional.',
      education: 'Ingeniero de Sistemas e Ingeniero Industrial, Universidad de los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 3,
    }),
  c('c24', 'Ixtli Yolot Barbosa', 'Consultor Senior', 'Associate',
    ['Agile', 'Digital Strategy', 'Lean', 'ERP', 'IT Strategy', 'Scrum Master'],
    '2026-05-29', null, null, {
      bio: 'Ixtli cuenta con experiencia en implementaciones Agile, desarrollo de planes estratégicos de TI y negocio, identificación de nuevas líneas de negocios digitales y optimización Lean de procesos.',
      education: 'Ingeniería de Sistemas, Universidad de Los Andes',
      years_of_experience: 2,
      certifications: ['Scrum Master Certificada'],
    }),
  c('c25', 'Juan David Yara', 'Associate', 'Associate',
    ['Strategy', 'Research', 'PowerPoint'],
    null),
  c('c26', 'Violeta Rodríguez', 'Asociada', 'Associate',
    ['Digital Transformation', 'IT Architecture', 'Software Selection', 'Gap Analysis', 'Technology Strategy'],
    null, null, null, {
      bio: 'Violeta cuenta con más de 3 años de experiencia en proyectos de transformación digital, definición de arquitectura, procesos de selección de soluciones tecnológicas y análisis de brechas.',
      languages: 'Español, Inglés',
      years_of_experience: 3,
    }),
  // Senior Consultants
  c('c27', 'Maria Camila González', 'Consultor Senior', 'Senior Consultant',
    ['Strategy', 'Financial Services', 'Telecoms', 'Oil & Gas', 'Business Analysis'],
    null, null, null, {
      bio: 'María Camila cuenta con 5+ años de experiencia en industria y en consultoría estratégica en los sectores financiero, oil & gas y telecomunicaciones.',
      languages: 'Español, Inglés, Francés',
    }),
  c('c28', 'Maria Camila Coronado', 'Consultor Senior', 'Senior Consultant',
    ['Operating Model Design', 'Process Improvement', 'Lean Six Sigma', 'Design Thinking', 'Operational Excellence'],
    '2026-08-21', null, null, {
      bio: 'María Camila cuenta con más de 5 años de experiencia en la transformación de modelos operativos y mejora de procesos en los sectores real y financiero, aplicando metodologías ágiles, Lean Six Sigma y Design Thinking.',
      years_of_experience: 5,
    }),
  c('c29', 'Maria Carolina De Lima', 'Consultor Senior - HRBP', 'Senior Consultant',
    ['Change Management', 'HR', 'Organizational Design', 'Training', 'Talent Management', 'Internal Communications'],
    '2026-07-31', null, null, {
      bio: 'María Carolina cuenta con más de 4 años de experiencia en equipos y procesos de talento humano, ejecutando proyectos de gestión del cambio, clima y cultura organizacional y desarrollo de personas.',
      education: 'Administradora de Empresas, Pontificia Universidad Javeriana',
      languages: 'Español, Inglés',
      years_of_experience: 4,
    }),
  c('c30', 'Nathalia Vélez', 'Consultor Senior', 'Senior Consultant',
    ['IT Strategy', 'Operational Excellence', 'Digital Transformation', 'Workforce Evolution', 'Strategic Planning'],
    '2026-11-30', null, null, {
      bio: 'Nathalia tiene más de 3 años de experiencia en planeación de estrategias de tecnología, excelencia operacional, programas de transformación operativa y evolución de la fuerza de trabajo.',
      education: 'Administradora de Empresas con énfasis en Innovación con Tecnología, Universidad de los Andes',
      languages: 'Español',
      years_of_experience: 3,
    }),
  c('c31', 'Juan David Alarcón', 'Consultor Senior', 'Senior Consultant',
    ['Web Development', 'Financial Modeling', 'Cloud (Azure/AWS)', 'Digital Transformation'],
    null, null, null, {
      bio: 'Juan David cuenta con experiencia en diseño e implementación de páginas web y desarrollo de modelos financieros para cumplir regulaciones del sector.',
      education: 'Ingeniero Biomédico e Ingeniero Mecánico, Universidad de los Andes',
      languages: 'Español, Inglés',
      certifications: ['Certificado Azure', 'Certificado AWS'],
    }),
  c('c32', 'María Crissien', 'Consultor Senior', 'Senior Consultant',
    ['Strategic Planning', 'Digital Transformation', 'Due Diligence', 'SAP S4/HANA', 'ERP', 'Oil & Gas'],
    '2026-11-30', null, null, {
      bio: 'Maria Alejandra cuenta con experiencia en planeación estratégica, transformación digital, due diligence y gestión e implementación de proyectos de tecnología (SAP S4/HANA Cloud) en sectores O&G, Insurtech, Fintech y holdings.',
      languages: 'Español, Inglés',
      years_of_experience: 1,
    }),
  c('c33', 'Fabian Becerra', 'Consultor Senior de Tecnología', 'Senior Consultant',
    ['Data Analytics', 'Risk Management', 'Financial Technology', 'Business Intelligence', 'AI', 'Data Engineering', 'Automation'],
    '2026-05-29', null, null, {
      bio: 'Fabian es Technology Consultant con experiencia en proyectos de analítica, riesgo y transformación tecnológica en el sector financiero, participando en iniciativas para entidades bancarias en América Latina y el Caribe.',
      years_of_experience: 3,
    }),
  c('c34', 'Nicolas Velez', 'Senior Consultant', 'Senior Consultant',
    ['Software Implementation', 'IT', 'Financial Consulting', 'PMO', 'Digital Transformation'],
    '2026-08-21', null, null, {
      bio: 'Nicolás tiene 4+ años de experiencia en consultoría y la industria financiera. Ha liderado proyectos cross-country para grandes corporaciones en España, Colombia y EEUU.',
      education: 'Ingeniero Industrial, Universidad de Los Andes · Minor en Matemáticas, Universidad de Los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 4,
    }),
  c('c35', 'Mateo Pimentel', 'Senior Consultant', 'Senior Consultant',
    ['Process Optimization', 'LEAN', 'Operations'],
    '2026-08-21'),
  c('c36', 'Diego Campos', 'Consultor Senior', 'Senior Consultant',
    ['Operating Model Design', 'Software Selection', 'IT Planning', 'Lean Six Sigma', 'Post-merger Integration'],
    '2026-11-30', null, null, {
      bio: 'Diego cuenta con experiencia en planeación y ejecución de proyectos de diseño de modelos operativos post-integración en los sectores financiero y O&G, así como en selección de software para el sector asegurador.',
      education: 'Administrador de Empresas y Especialista en Inteligencia de Mercados con opción en Derecho de los Negocios, Universidad de los Andes',
      languages: 'Español, Inglés',
      certifications: ['Lean Six Sigma Yellow Belt'],
    }),
  c('c37', 'Juan Felipe Patiño', 'Consultor', 'Senior Consultant',
    ['Product Strategy', 'Software Development', 'IT Consulting', 'Product Management', 'Vendor Management'],
    '2026-11-30', null, null, {
      bio: 'Juan Felipe cuenta con experiencia en desarrollo de productos, estrategia de producto, desarrollo de software y relacionamiento con proveedores.',
      education: 'Ingeniero Industrial e Ingeniero de Sistemas y Computación con opción en Derecho de los Negocios, Universidad de los Andes',
      languages: 'Español, Inglés',
      years_of_experience: 1,
    }),
  c('c38', 'David Rincón', 'Senior Consultant', 'Senior Consultant',
    ['Digital Transformation', 'IT Strategy', 'Cloud'],
    '2026-11-30'),
  c('c39', 'Daniel Ángel', 'Senior Consultant', 'Senior Consultant',
    ['Change Management', 'Communications', 'Training'],
    '2026-12-31'),
  c('c40', 'Gabriela García', 'Senior Consultant', 'Senior Consultant',
    ['Business Analysis', 'Process Mapping', 'Visio'],
    '2026-11-30'),
  c('c41', 'Laura Forero', 'Senior Consultant', 'Senior Consultant',
    ['Data Analytics', 'Power BI', 'SQL'],
    '2026-11-30'),
  // Consultants
  c('c42', 'Lina María Gómez', 'Consultant', 'Consultant',
    ['Research', 'Excel', 'PowerPoint'],
    null),
  c('c43', 'Juan Felipe Sánchez', 'Consultant', 'Consultant',
    ['Business Analysis', 'Research', 'Excel'],
    '2026-08-21'),
  c('c44', 'Nathalia Quiroga', 'Consultant', 'Consultant',
    ['Data Analytics', 'SQL', 'Python'],
    null),
  c('c45', 'Sebastian Gomez', 'Consultant', 'Consultant',
    ['Process Optimization', 'Operations', 'Excel'],
    '2026-12-31'),
  c('c46', 'Andrés Villota', 'Consultant', 'Consultant',
    ['Financial Modeling', 'Research', 'PowerPoint'],
    '2026-11-30'),
  c('c47', 'Juan Currea', 'Consultant', 'Consultant',
    ['Digital Transformation', 'IT', 'Research'],
    null),
  c('c48', 'Julián Cardenas', 'Consultant', 'Consultant',
    ['Change Management', 'Communications', 'Training'],
    null),
  c('c49', 'Emilio Baquerizo', 'Consultant', 'Consultant',
    ['Strategy', 'Research', 'Excel'],
    null),
  c('c50', 'Santiago Arevalo', 'Consultant', 'Consultant',
    ['Data Analytics', 'Power BI', 'SQL'],
    '2026-11-30'),
  c('c51', 'Matias Bermudez', 'Consultant', 'Consultant',
    ['Business Analysis', 'Process Mapping', 'Visio'],
    '2026-05-29'),
  c('c52', 'Juana Mejia', 'Consultant', 'Consultant',
    ['Organizational Design', 'HR', 'Research'],
    null),
  c('c53', 'Sophie Tobias', 'Consultant', 'Consultant',
    ['Project Management', 'Agile', 'Communications'],
    '2026-12-31'),
  c('c54', 'Manuela Lizcano', 'Consultant', 'Consultant',
    ['Financial Modeling', 'Research', 'Excel'],
    '2026-11-30'),
  c('c55', 'Giuliana Volpi', 'Consultor', 'Consultant',
    ['Data Analytics', 'Machine Learning', 'Advanced Analytics', 'Python', 'Data Architecture'],
    '2026-05-29', null, null, {
      bio: 'Giuliana cuenta con experiencia como Data Analyst y ejecución de proyectos de analítica avanzada, machine learning y arquitectura de soluciones.',
      languages: 'Español, Inglés, Italiano',
    }),
  c('c56', 'Juan Felipe Puig', 'Consultant', 'Consultant',
    ['Digital Transformation', 'IT', 'Agile'],
    '2026-11-30'),
  // Interns
  c('c57', 'Juan Manuel Perez', 'Intern', 'Intern',
    ['Research', 'Excel', 'PowerPoint'],
    '2026-11-30', null, '2026-07-31'),
  c('c58', 'Maria Fernanda Amador', 'Intern', 'Intern',
    ['Research', 'Excel', 'Data Analytics'],
    '2026-06-12', null, '2026-07-31'),
  c('c59', 'Amalia Carbonell', 'Intern', 'Intern',
    ['Research', 'PowerPoint', 'Communications'],
    null, null, '2026-07-31'),
  c('c60', 'Santiago Celis', 'Practicante de Consultoría en TI', 'Intern',
    ['AI/GenAI', 'Platform Development', 'Data Analysis', 'UX', 'Systems Engineering'],
    null, null, '2026-07-31', {
      bio: 'Santiago cuenta con experiencia en desarrollo y soporte de plataformas tecnológicas, con foco en mejora de la experiencia del usuario, soluciones basadas en IA generativa y análisis de datos.',
      education: 'Ingeniería de Sistemas y Computación, Universidad de los Andes',
      languages: 'Español, Inglés',
    }),
  c('c61', 'Sofia Correa', 'Intern', 'Intern',
    ['Research', 'Excel', 'PowerPoint'],
    null, null, '2026-07-31'),
]

// Projects — sourced from SAP-Kimble export
export const mockProjects: Project[] = [
  {
    id: 'p711',
    name: 'Consolidación Aval Asset Management',
    client: 'Aval Fiduciaria',
    industry: 'Financial Services',
    description: 'Asset management consolidation and operating model design.',
    status: 'Active',
    start_date: '2026-02-09',
    end_date: '2026-11-30',
    team_size: 21,
    skills_required: ['Financial Modeling', 'Operations', 'Change Management', 'Project Management'],
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'p713',
    name: 'Proyecto Cóndor',
    client: 'Banco de Bogotá',
    industry: 'Financial Services',
    description: 'Comprehensive strategic and operational transformation program.',
    status: 'Active',
    start_date: '2026-02-12',
    end_date: '2026-12-31',
    team_size: 12,
    skills_required: ['Strategy', 'Change Management', 'Project Management', 'Business Analysis', 'Stakeholder Management'],
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'p600',
    name: 'Selección y Gap Analysis ERP LATAM',
    client: 'Holcim',
    industry: 'Manufacturing',
    description: 'ERP vendor selection and gap analysis across LATAM operations.',
    status: 'Active',
    start_date: '2026-01-05',
    end_date: '2026-08-21',
    team_size: 8,
    skills_required: ['ERP', 'SAP', 'Business Analysis', 'Project Management', 'Data Analytics'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p608',
    name: 'Implementación Core',
    client: 'Pacífico Seguros',
    industry: 'Insurance',
    description: 'Core insurance platform implementation.',
    status: 'Active',
    start_date: '2026-01-05',
    end_date: '2026-05-29',
    team_size: 7,
    skills_required: ['Implementation', 'Business Analysis', 'IT Strategy', 'Project Management'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p712',
    name: 'GAP Análisis',
    client: 'D1',
    industry: 'Retail',
    description: 'ERP gap analysis for retail operations.',
    status: 'Active',
    start_date: '2026-02-09',
    end_date: '2026-04-17',
    team_size: 4,
    skills_required: ['ERP', 'Business Analysis', 'Process Optimization'],
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'p704',
    name: 'Interim Security Role Fase 2',
    client: 'Aruba Bank',
    industry: 'Financial Services',
    description: 'Cybersecurity interim management and controls implementation.',
    status: 'Active',
    start_date: '2026-01-05',
    end_date: '2026-04-03',
    team_size: 4,
    skills_required: ['Cybersecurity', 'IT Strategy', 'Risk Management'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p702',
    name: 'Estrategia de Negocio',
    client: 'PersonalSoft',
    industry: 'Technology',
    description: 'Business strategy definition and go-to-market planning.',
    status: 'Active',
    start_date: '2026-02-09',
    end_date: '2026-04-03',
    team_size: 4,
    skills_required: ['Strategy', 'Business Analysis', 'Financial Modeling'],
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'p691',
    name: 'Consolidación y Evolución ERP/DMS',
    client: 'Autogermana',
    industry: 'Automotive',
    description: 'ERP and DMS consolidation project.',
    status: 'Active',
    start_date: '2026-02-17',
    end_date: '2026-03-17',
    team_size: 3,
    skills_required: ['ERP', 'Business Analysis', 'Change Management'],
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'p690',
    name: 'Delfos',
    client: 'Grupo AVAL',
    industry: 'Financial Services',
    description: 'Strategic analytics and forecasting platform.',
    status: 'Active',
    start_date: '2026-01-02',
    end_date: '2026-03-18',
    team_size: 3,
    skills_required: ['Data Analytics', 'Strategy', 'Business Intelligence'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p688',
    name: 'Implementación Estrategia CIAM',
    client: 'Compensar',
    industry: 'Healthcare',
    description: 'Customer Identity and Access Management strategy implementation.',
    status: 'Active',
    start_date: '2026-01-13',
    end_date: '2026-01-30',
    team_size: 3,
    skills_required: ['Cybersecurity', 'IT Strategy', 'Implementation'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p681',
    name: 'Revisión del Modelo Comercial',
    client: 'Pacífico Seguros',
    industry: 'Insurance',
    description: 'Commercial operating model review and redesign.',
    status: 'Active',
    start_date: '2026-01-12',
    end_date: '2026-02-20',
    team_size: 2,
    skills_required: ['Strategy', 'Organizational Design', 'Business Analysis'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p668',
    name: 'Kronos Acompañamiento Implementación',
    client: 'Corficolombiana',
    industry: 'Financial Services',
    description: 'Workforce management system implementation support.',
    status: 'Active',
    start_date: '2026-01-05',
    end_date: '2026-02-20',
    team_size: 8,
    skills_required: ['Implementation', 'Change Management', 'Training'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p604',
    name: 'Estrategia de Integración',
    client: 'Kairos',
    industry: 'Technology',
    description: 'Integration strategy for technology platforms.',
    status: 'Active',
    start_date: '2026-01-02',
    end_date: '2026-02-06',
    team_size: 18,
    skills_required: ['IT Strategy', 'Systems Architecture', 'Project Management'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'p594',
    name: 'Gap Analysis Implementación ERP',
    client: 'OLCSAL',
    industry: 'Manufacturing',
    description: 'ERP implementation gap analysis for manufacturing operations.',
    status: 'Active',
    start_date: '2026-01-05',
    end_date: '2026-01-30',
    team_size: 2,
    skills_required: ['ERP', 'Business Analysis', 'Manufacturing'],
    created_at: '2026-01-01T00:00:00Z',
  },
  // ── Open projects pending staffing ──
  {
    id: 'p801',
    name: 'Transformación Digital Retail',
    client: 'Éxito Group',
    industry: 'Retail',
    description: 'End-to-end digital transformation including e-commerce, loyalty platform and operational systems modernization.',
    status: 'Open',
    start_date: '2026-05-15',
    end_date: '2026-12-15',
    team_size: 4,
    skills_required: ['Digital Transformation', 'IT Strategy', 'Business Analysis', 'Change Management'],
    created_at: '2026-04-20T00:00:00Z',
  },
  {
    id: 'p802',
    name: 'Estrategia de Datos y Analytics',
    client: 'Bancolombia',
    industry: 'Financial Services',
    description: 'Data strategy and advanced analytics roadmap to support credit risk and customer intelligence initiatives.',
    status: 'Partially Staffed',
    start_date: '2026-05-04',
    end_date: '2026-09-30',
    team_size: 3,
    skills_required: ['Data Analytics', 'Business Intelligence', 'Strategy', 'Financial Services'],
    created_at: '2026-04-15T00:00:00Z',
  },
  {
    id: 'p803',
    name: 'Selección ERP Sector Salud',
    client: 'Clínica del Country',
    industry: 'Healthcare',
    description: 'ERP vendor evaluation and selection for clinical and administrative operations.',
    status: 'Open',
    start_date: '2026-06-01',
    end_date: '2026-10-31',
    team_size: 3,
    skills_required: ['ERP', 'Business Analysis', 'Project Management', 'Healthcare'],
    created_at: '2026-04-25T00:00:00Z',
  },
]

// Real assignments from SAP-Kimble — only active (end_date >= 2026-04-20)
export const mockAssignments: ProjectAssignment[] = [
  // ── Aval Fiduciaria — Consolidación Aval Asset Management ──
  { id: 'a01', project_id: 'p711', consultant_id: 'c1',  dedication_percentage: 30,  end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a02', project_id: 'p711', consultant_id: 'c4',  dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a03', project_id: 'p711', consultant_id: 'c7',  dedication_percentage: 40,  end_date: '2026-07-31', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a04', project_id: 'p711', consultant_id: 'c6',  dedication_percentage: 50,  end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a05', project_id: 'p711', consultant_id: 'c12', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a06', project_id: 'p711', consultant_id: 'c17', dedication_percentage: 50,  end_date: '2026-11-30', assigned_at: '2026-02-23T00:00:00Z' },
  { id: 'a07', project_id: 'p711', consultant_id: 'c19', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a08', project_id: 'p711', consultant_id: 'c23', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a09', project_id: 'p711', consultant_id: 'c30', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-16T00:00:00Z' },
  { id: 'a10', project_id: 'p711', consultant_id: 'c29', dedication_percentage: 100, end_date: '2026-07-31', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a11', project_id: 'p711', consultant_id: 'c32', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a12', project_id: 'p711', consultant_id: 'c46', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a13', project_id: 'p711', consultant_id: 'c40', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a14', project_id: 'p711', consultant_id: 'c36', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a15', project_id: 'p711', consultant_id: 'c56', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-12T00:00:00Z' },
  { id: 'a16', project_id: 'p711', consultant_id: 'c41', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a17', project_id: 'p711', consultant_id: 'c37', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a18', project_id: 'p711', consultant_id: 'c54', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  { id: 'a19', project_id: 'p711', consultant_id: 'c50', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-03-02T00:00:00Z' },
  { id: 'a20', project_id: 'p711', consultant_id: 'c38', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-23T00:00:00Z' },
  { id: 'a21', project_id: 'p711', consultant_id: 'c57', dedication_percentage: 100, end_date: '2026-11-30', assigned_at: '2026-02-09T00:00:00Z' },
  // ── Banco de Bogotá — Proyecto Cóndor ──
  { id: 'a22', project_id: 'p713', consultant_id: 'c1',  dedication_percentage: 20,  end_date: '2026-12-31', assigned_at: '2026-02-12T00:00:00Z' },
  { id: 'a23', project_id: 'p713', consultant_id: 'c2',  dedication_percentage: 50,  end_date: '2026-12-31', assigned_at: '2026-02-12T00:00:00Z' },
  { id: 'a24', project_id: 'p713', consultant_id: 'c6',  dedication_percentage: 50,  end_date: '2026-12-31', assigned_at: '2026-02-12T00:00:00Z' },
  { id: 'a25', project_id: 'p713', consultant_id: 'c8',  dedication_percentage: 100, end_date: '2026-12-31', assigned_at: '2026-02-12T00:00:00Z' },
  { id: 'a26', project_id: 'p713', consultant_id: 'c14', dedication_percentage: 100, end_date: '2026-12-31', assigned_at: '2026-02-16T00:00:00Z' },
  { id: 'a27', project_id: 'p713', consultant_id: 'c16', dedication_percentage: 100, end_date: '2026-12-31', assigned_at: '2026-02-25T00:00:00Z' },
  { id: 'a28', project_id: 'p713', consultant_id: 'c22', dedication_percentage: 100, end_date: '2026-12-31', assigned_at: '2026-02-12T00:00:00Z' },
  { id: 'a29', project_id: 'p713', consultant_id: 'c53', dedication_percentage: 100, end_date: '2026-12-31', assigned_at: '2026-02-25T00:00:00Z' },
  { id: 'a30', project_id: 'p713', consultant_id: 'c45', dedication_percentage: 100, end_date: '2026-12-31', assigned_at: '2026-02-16T00:00:00Z' },
  { id: 'a31', project_id: 'p713', consultant_id: 'c39', dedication_percentage: 100, end_date: '2026-12-31', assigned_at: '2026-02-16T00:00:00Z' },
  { id: 'a32', project_id: 'p713', consultant_id: 'c55', dedication_percentage: 100, end_date: '2026-05-29', assigned_at: '2026-02-16T00:00:00Z' },
  { id: 'a33', project_id: 'p713', consultant_id: 'c58', dedication_percentage: 100, end_date: '2026-06-12', assigned_at: '2026-02-16T00:00:00Z' },
  // ── Holcim — ERP LATAM ──
  { id: 'a34', project_id: 'p600', consultant_id: 'c3',  dedication_percentage: 15,  end_date: '2026-08-21', assigned_at: '2026-01-13T00:00:00Z' },
  { id: 'a35', project_id: 'p600', consultant_id: 'c9',  dedication_percentage: 50,  end_date: '2026-08-21', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a36', project_id: 'p600', consultant_id: 'c10', dedication_percentage: 100, end_date: '2026-08-21', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a37', project_id: 'p600', consultant_id: 'c15', dedication_percentage: 100, end_date: '2026-08-21', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a38', project_id: 'p600', consultant_id: 'c28', dedication_percentage: 100, end_date: '2026-08-21', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a39', project_id: 'p600', consultant_id: 'c34', dedication_percentage: 100, end_date: '2026-08-21', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a40', project_id: 'p600', consultant_id: 'c35', dedication_percentage: 100, end_date: '2026-08-21', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a41', project_id: 'p600', consultant_id: 'c43', dedication_percentage: 100, end_date: '2026-08-21', assigned_at: '2026-01-13T00:00:00Z' },
  // ── Pacífico Seguros — Implementación Core ──
  { id: 'a42', project_id: 'p608', consultant_id: 'c3',  dedication_percentage: 20,  end_date: '2026-05-29', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a43', project_id: 'p608', consultant_id: 'c5',  dedication_percentage: 100, end_date: '2026-05-29', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a44', project_id: 'p608', consultant_id: 'c17', dedication_percentage: 50,  end_date: '2026-05-29', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a45', project_id: 'p608', consultant_id: 'c21', dedication_percentage: 100, end_date: '2026-05-29', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a46', project_id: 'p608', consultant_id: 'c24', dedication_percentage: 100, end_date: '2026-05-29', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a47', project_id: 'p608', consultant_id: 'c33', dedication_percentage: 100, end_date: '2026-05-29', assigned_at: '2026-01-05T00:00:00Z' },
  { id: 'a48', project_id: 'p608', consultant_id: 'c51', dedication_percentage: 100, end_date: '2026-05-29', assigned_at: '2026-01-05T00:00:00Z' },
]

export const mockVacationRequests: VacationRequest[] = [
  {
    id: 'v1',
    consultant_id: 'c1',
    start_date: '2026-05-05',
    end_date: '2026-05-09',
    note: 'Family vacation',
    status: 'Approved',
    reviewed_by: 'hr1',
    reviewed_at: '2026-04-01T00:00:00Z',
    created_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'v2',
    consultant_id: 'c2',
    start_date: '2026-04-28',
    end_date: '2026-04-30',
    note: 'Personal days',
    status: 'Pending',
    created_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'v3',
    consultant_id: 'c6',
    start_date: '2026-05-19',
    end_date: '2026-05-23',
    status: 'Pending',
    created_at: '2026-04-12T00:00:00Z',
  },
]

export const mockLikes: ProjectLike[] = []

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    user_id: 'c1',
    type: 'vacation_approved',
    title: 'Vacation Approved',
    body: 'Your vacation request for May 5–9 has been approved.',
    read: false,
    created_at: '2026-04-01T00:00:00Z',
  },
]

export const DEMO_USERS = {
  'consultant@bip.com': {
    password: 'demo123',
    profile: mockConsultants[0], // Hernando Baquero
  },
  'hr@bip.com': {
    password: 'demo123',
    profile: {
      id: 'hr1',
      name: 'María Rodríguez',
      role_title: 'HR Manager',
      seniority: 'Director' as const,
      practice_area: null,
      skills: ['HR', 'Staffing', 'People Management'],
      available_from: null,
      internship_start_date: null,
      internship_end_date: null,
      user_role: 'hr_admin' as const,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
      bio: null, education: null, languages: null, years_of_experience: null, certifications: [], experience: [],
    },
  },
}
