// Run with: node scripts/generate-seed.mjs > scripts/seed.sql
// Then paste seed.sql into Supabase SQL editor

const consultants = [
  { id:'c1',  name:'Hernando Baquero',        role_title:'Senior Partner',                          seniority:'Senior Partner',    skills:['Digital Transformation','Operational Excellence','IT Strategy','Strategic Planning','Business Intelligence','Post-merger Integration'], available_from:'2026-12-31', bio:'Hernando tiene más de 20 años de experiencia en transformación digital, excelencia operativa, planificación estratégica de negocios y TI y gestión de proyectos complejos. Antes de fundar Advantis en 2003, fue consultor en Booz Allen Hamilton y Gerente de una empresa de consultoría colombiana.', education:'Ingeniero Industrial, Universidad de los Andes · MBA, INSEAD', languages:'Español, Inglés', years_of_experience:20, certifications:[], experience:[{id:'e1a',title:'Transformación Digital y Tecnologías de la Información',client:'Sector Financiero, LATAM',period:'2003 – presente',description:'Soporte en Transformación Digital — mejora de la experiencia del cliente, modernización de aplicaciones heredadas y excelencia operativa.'},{id:'e1b',title:'Transformación Organizacional',client:'Banca y Sector Real',period:'2003 – presente',description:'Integración post-fusión de bancos, fondos de pensiones y empresas de consumo con énfasis en TI.'}] },
  { id:'c2',  name:'John Jairo Romero',         role_title:'Partner',                                 seniority:'Partner',           skills:['Digital Transformation','IT Strategy','Cybersecurity','M&A','Financial Services','Process Improvement'], available_from:'2026-12-31', bio:'John Jairo ha dedicado su carrera de más de 27 años en consultoría a ayudar a empresas en múltiples industrias a transformar su negocio mediante tecnología e innovación digital.', education:'Ingeniero de Sistemas, Universidad de Los Andes', languages:'Español, Inglés', years_of_experience:27, certifications:[], experience:[] },
  { id:'c3',  name:'Juan Fernando Forero',      role_title:'Partner',                                 seniority:'Partner',           skills:['IT Planning','IT Management','Systems Architecture','Project Management','Software Selection','Integration'], available_from:'2026-08-21', bio:'Juan Fernando cuenta con más de 30 años de experiencia en consultoría gerencial para resolver asuntos estratégicos de TI.', education:'Ingeniero de Sistemas y Computación, Universidad de Los Andes', languages:'Español, Inglés', years_of_experience:30, certifications:[], experience:[] },
  { id:'c4',  name:'Henry Jaimes',              role_title:'Director',                                seniority:'Director',          skills:['IT Strategy','IT Architecture','Digital Transformation','Organizational Design','Agile','Due Diligence'], available_from:'2026-11-30', bio:'Henry tiene una amplia experiencia en consultoría en estrategia de tecnología y negocios, arquitectura de TI, implementación de estrategias de transformación digital.', education:'Ingeniero de Sistemas, Universidad de Los Andes · Magíster en Tecnologías de la Información para el Negocio', languages:'Español, Inglés', years_of_experience:null, certifications:['Scrum Master Certificado'], experience:[] },
  { id:'c5',  name:'Andrés Cubillos',           role_title:'Senior Manager',                          seniority:'Senior Manager',    skills:['Operational Excellence','IT Strategy','Enterprise Architecture','Agile','Software Implementation','Process Optimization'], available_from:'2026-05-29', bio:'Andrés tiene más de 12 años de experiencia enfocándose en dirección de proyectos complejos, planeación de TI, modelos de gestión y transformación de modelos operativos.', education:'Ingeniero, Universidad de Los Andes', languages:null, years_of_experience:12, certifications:[], experience:[] },
  { id:'c6',  name:'Jaime Barco',               role_title:'Experto Datos y Analítica',               seniority:'Senior Manager',    skills:['Data Analytics','Data Mining','Business Intelligence','AI/ML','Data Quality','Data Strategy'], available_from:'2026-12-31', bio:'Jaime ha participado en más de 80 proyectos relacionados con Data y Analítica. Especialista en técnicas de minería de datos, calidad de datos e implantación de sistemas de inteligencia artificial.', education:'Ingeniero de Sistemas, Universidad Autónoma de Manizales · Especialización en Desarrollo Gerencial · PDD, INALDE', languages:'Español, Portugués', years_of_experience:20, certifications:[], experience:[] },
  { id:'c7',  name:'Carla Villaverde',          role_title:'Directora Talento Humano',                seniority:'Senior Manager',    skills:['HR Strategy','Talent Acquisition','Organizational Design','Employer Branding','Engagement Strategy','Change Management'], available_from:'2026-07-31', bio:'Carla cuenta con más de 15 años de experiencia en talento humano, trabajando en la definición e implementación de estrategias que apalanquen los objetivos del negocio.', education:null, languages:'Español, Inglés', years_of_experience:15, certifications:[], experience:[] },
  { id:'c8',  name:'Felipe Estrada',            role_title:'Senior Manager',                          seniority:'Senior Manager',    skills:['Digital Transformation','IT Strategy','Data Strategy','IT Architecture','Business Strategy'], available_from:'2026-12-31', bio:'Felipe tiene 10+ años de experiencia. Anteriormente trabajó en IBM Colombia como consultor de TI.', education:'Ingeniero en Sistemas e Informática, Universidad de los Andes', languages:'Español, Inglés', years_of_experience:10, certifications:['Scrum Master Certificado'], experience:[] },
  { id:'c9',  name:'Iván Melo',                 role_title:'Gerente Senior – Especialista Arquitectura TI', seniority:'Senior Manager', skills:['IT Architecture','Enterprise Architecture','Digital Transformation','IT Strategy','Software Selection','Financial Services'], available_from:'2026-08-21', bio:'Iván Mauricio tiene 15+ años de experiencia en proyectos de arquitectura empresarial y asuntos estratégicos de TI.', education:'Máster en Ingeniería e Ingeniero de Sistemas y Computación, Universidad de Los Andes', languages:'Español, Inglés', years_of_experience:15, certifications:[], experience:[] },
  { id:'c10', name:'Magda Patiño',              role_title:'Especialista en Gestión de Proyectos',    seniority:'Manager',           skills:['Project Management','Software Implementation','Change Management','QA','ERP'], available_from:'2026-08-21', bio:'Magda es Especialista de Gestión de Proyectos con más de 25 años de experiencia en implementación de soluciones informáticas.', education:'Ingeniera de Sistemas, Universidad de Los Andes', languages:null, years_of_experience:25, certifications:['Scrum Master Certificada'], experience:[] },
  { id:'c11', name:'Alejandro Manrique',        role_title:'Manager',                                 seniority:'Manager',           skills:['Strategy','Business Analysis','Financial Modeling'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c12', name:'John Casallas',             role_title:'Manager',                                 seniority:'Manager',           skills:['Project Management','Software Implementation','IT Strategy','Enterprise Architecture','Digital Transformation','Business Process Automation'], available_from:'2026-11-30', bio:'John cuenta con 13+ años de experiencia. Sus principales áreas de especialización son gestión de proyectos de implementación de software y arquitectura empresarial.', education:'Ingeniero de Sistemas, Universidad de Los Andes · Magíster en Ingeniería de Sistemas', languages:null, years_of_experience:13, certifications:[], experience:[] },
  { id:'c13', name:'Felipe Mediorreal',         role_title:'Manager',                                 seniority:'Manager',           skills:['Operations','Supply Chain','Process Optimization'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c14', name:'Santiago Serna',            role_title:'Manager',                                 seniority:'Manager',           skills:['Business Strategy','Digital Transformation','Operational Excellence','Agile Transformation'], available_from:'2026-12-31', bio:'Santiago Serna cuenta con más de 8 años de experiencia en proyectos de estrategia de negocios, transformación digital, gestión de tecnología y excelencia operacional.', education:'MBA, Duke University · Ingeniero Industrial y Civil, Universidad de Los Andes', languages:'Español, Inglés', years_of_experience:8, certifications:[], experience:[] },
  { id:'c15', name:'Angélica Tarazona',         role_title:'Manager',                                 seniority:'Manager',           skills:['HR','Finance','Organizational Design','Change Management','Talent Management'], available_from:'2026-08-21', bio:null, education:'Magíster en Finanzas, Universidad de Los Andes · Administradora y Economista, Universidad Metropolitana (Caracas)', languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c16', name:'Andrea Rosales',            role_title:'Senior Associate',                        seniority:'Senior Associate',  skills:['Business Analysis','Process Optimization','Excel'], available_from:'2026-12-31', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c17', name:'Guillermo Ferro',           role_title:'Asociado Senior',                         seniority:'Senior Associate',  skills:['IT Strategy','IT Architecture','Digital Transformation','Enterprise Architecture'], available_from:'2026-11-30', bio:null, education:'Magíster en Arquitectura de TI, Universidad de los Andes', languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c18', name:'Diego Castro',              role_title:'Asociado',                                seniority:'Senior Associate',  skills:['IT Strategy','Digital Transformation','Agile','Lean Digital','Organizational Strategy'], available_from:null, bio:'Diego Castro cuenta con 4 años de experiencia en proyectos de estrategia de tecnología y negocio, estrategia organizacional, implementación de metodologías ágiles y lean digital.', education:null, languages:'Español, Inglés', years_of_experience:4, certifications:[], experience:[] },
  { id:'c19', name:'Raúl Aular',                role_title:'Asociado',                                seniority:'Associate',         skills:['IT Management','Strategic Planning','Process Management','ERP','Turnaround','Retail'], available_from:'2026-11-30', bio:'Raúl cuenta con experiencia en implementación de modelos de gestión de TI, rediseño e implementación de procesos y planes de turnaround.', education:null, languages:'Español, Inglés, Portugués', years_of_experience:null, certifications:[], experience:[] },
  { id:'c20', name:'Lina Gutiérrez',            role_title:'Senior Associate',                        seniority:'Senior Associate',  skills:['Change Management','Training','Communications'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c21', name:'Juan David Figueroa',       role_title:'Asociado Sr',                             seniority:'Senior Associate',  skills:['Business Strategy','Digital Transformation','Process Optimization','Operating Model Design','Financial Efficiency'], available_from:'2026-05-29', bio:'Juan David cuenta con más de 6 años de experiencia en estrategia de negocio y tecnología, transformación digital y optimización de procesos.', education:'Economista, Pontificia Universidad Javeriana', languages:'Español, Inglés', years_of_experience:6, certifications:[], experience:[] },
  { id:'c22', name:'Antonio Pérez',             role_title:'Asociado',                                seniority:'Associate',         skills:['Digital Transformation','ERP','CRM','IT Strategy','Energy','Carve-out'], available_from:'2026-12-31', bio:'Antonio tiene más de 6 años de experiencia en consultoría estratégica y de operaciones en los sectores de energía, utilities y servicios financieros.', education:null, languages:'Español (nativo), Inglés C1', years_of_experience:6, certifications:[], experience:[] },
  { id:'c23', name:'Santiago Restrepo',         role_title:'Consultor Senior',                        seniority:'Associate',         skills:['Digital Transformation','Software Implementation','IT Strategy','Operational Excellence','Strategic Planning'], available_from:'2026-11-30', bio:'Santiago cuenta con 3 años de experiencia en proyectos de transformación digital, implementación de software, definición de estrategia de tecnología y excelencia operacional.', education:'Ingeniero de Sistemas e Ingeniero Industrial, Universidad de los Andes', languages:'Español, Inglés', years_of_experience:3, certifications:[], experience:[] },
  { id:'c24', name:'Ixtli Yolot Barbosa',       role_title:'Consultor Senior',                        seniority:'Associate',         skills:['Agile','Digital Strategy','Lean','ERP','IT Strategy','Scrum Master'], available_from:'2026-05-29', bio:'Ixtli cuenta con experiencia en implementaciones Agile, desarrollo de planes estratégicos de TI y negocio.', education:'Ingeniería de Sistemas, Universidad de Los Andes', languages:null, years_of_experience:2, certifications:['Scrum Master Certificada'], experience:[] },
  { id:'c25', name:'Juan David Yara',           role_title:'Associate',                               seniority:'Associate',         skills:['Strategy','Research','PowerPoint'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c26', name:'Violeta Rodríguez',         role_title:'Asociada',                                seniority:'Associate',         skills:['Digital Transformation','IT Architecture','Software Selection','Gap Analysis','Technology Strategy'], available_from:null, bio:'Violeta cuenta con más de 3 años de experiencia en proyectos de transformación digital, definición de arquitectura, procesos de selección de soluciones tecnológicas.', education:null, languages:'Español, Inglés', years_of_experience:3, certifications:[], experience:[] },
  { id:'c27', name:'Maria Camila González',     role_title:'Consultor Senior',                        seniority:'Senior Consultant', skills:['Strategy','Financial Services','Telecoms','Oil & Gas','Business Analysis'], available_from:null, bio:'María Camila cuenta con 5+ años de experiencia en industria y en consultoría estratégica en los sectores financiero, oil & gas y telecomunicaciones.', education:null, languages:'Español, Inglés, Francés', years_of_experience:null, certifications:[], experience:[] },
  { id:'c28', name:'Maria Camila Coronado',     role_title:'Consultor Senior',                        seniority:'Senior Consultant', skills:['Operating Model Design','Process Improvement','Lean Six Sigma','Design Thinking','Operational Excellence'], available_from:'2026-08-21', bio:'María Camila cuenta con más de 5 años de experiencia en la transformación de modelos operativos y mejora de procesos.', education:null, languages:null, years_of_experience:5, certifications:[], experience:[] },
  { id:'c29', name:'Maria Carolina De Lima',    role_title:'Consultor Senior - HRBP',                 seniority:'Senior Consultant', skills:['Change Management','HR','Organizational Design','Training','Talent Management','Internal Communications'], available_from:'2026-07-31', bio:'María Carolina cuenta con más de 4 años de experiencia en equipos y procesos de talento humano.', education:'Administradora de Empresas, Pontificia Universidad Javeriana', languages:'Español, Inglés', years_of_experience:4, certifications:[], experience:[] },
  { id:'c30', name:'Nathalia Vélez',            role_title:'Consultor Senior',                        seniority:'Senior Consultant', skills:['IT Strategy','Operational Excellence','Digital Transformation','Workforce Evolution','Strategic Planning'], available_from:'2026-11-30', bio:'Nathalia tiene más de 3 años de experiencia en planeación de estrategias de tecnología, excelencia operacional y programas de transformación operativa.', education:'Administradora de Empresas con énfasis en Innovación con Tecnología, Universidad de los Andes', languages:'Español', years_of_experience:3, certifications:[], experience:[] },
  { id:'c31', name:'Juan David Alarcón',        role_title:'Consultor Senior',                        seniority:'Senior Consultant', skills:['Web Development','Financial Modeling','Cloud (Azure/AWS)','Digital Transformation'], available_from:null, bio:'Juan David cuenta con experiencia en diseño e implementación de páginas web y desarrollo de modelos financieros.', education:'Ingeniero Biomédico e Ingeniero Mecánico, Universidad de los Andes', languages:'Español, Inglés', years_of_experience:null, certifications:['Certificado Azure','Certificado AWS'], experience:[] },
  { id:'c32', name:'María Crissien',            role_title:'Consultor Senior',                        seniority:'Senior Consultant', skills:['Strategic Planning','Digital Transformation','Due Diligence','SAP S4/HANA','ERP','Oil & Gas'], available_from:'2026-11-30', bio:'Maria Alejandra cuenta con experiencia en planeación estratégica, transformación digital, due diligence y gestión e implementación de proyectos de tecnología.', education:null, languages:'Español, Inglés', years_of_experience:1, certifications:[], experience:[] },
  { id:'c33', name:'Fabian Becerra',            role_title:'Consultor Senior de Tecnología',          seniority:'Senior Consultant', skills:['Data Analytics','Risk Management','Financial Technology','Business Intelligence','AI','Data Engineering','Automation'], available_from:'2026-05-29', bio:'Fabian es Technology Consultant con experiencia en proyectos de analítica, riesgo y transformación tecnológica en el sector financiero.', education:null, languages:null, years_of_experience:3, certifications:[], experience:[] },
  { id:'c34', name:'Nicolas Velez',             role_title:'Senior Consultant',                       seniority:'Senior Consultant', skills:['Software Implementation','IT','Financial Consulting','PMO','Digital Transformation'], available_from:'2026-08-21', bio:'Nicolás tiene 4+ años de experiencia en consultoría y la industria financiera. Ha liderado proyectos cross-country para grandes corporaciones.', education:'Ingeniero Industrial, Universidad de Los Andes · Minor en Matemáticas', languages:'Español, Inglés', years_of_experience:4, certifications:[], experience:[] },
  { id:'c35', name:'Mateo Pimentel',            role_title:'Senior Consultant',                       seniority:'Senior Consultant', skills:['Process Optimization','LEAN','Operations'], available_from:'2026-08-21', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c36', name:'Diego Campos',              role_title:'Consultor Senior',                        seniority:'Senior Consultant', skills:['Operating Model Design','Software Selection','IT Planning','Lean Six Sigma','Post-merger Integration'], available_from:'2026-11-30', bio:'Diego cuenta con experiencia en planeación y ejecución de proyectos de diseño de modelos operativos post-integración.', education:'Administrador de Empresas y Especialista en Inteligencia de Mercados, Universidad de los Andes', languages:'Español, Inglés', years_of_experience:null, certifications:['Lean Six Sigma Yellow Belt'], experience:[] },
  { id:'c37', name:'Juan Felipe Patiño',        role_title:'Consultor',                               seniority:'Senior Consultant', skills:['Product Strategy','Software Development','IT Consulting','Product Management','Vendor Management'], available_from:'2026-11-30', bio:'Juan Felipe cuenta con experiencia en desarrollo de productos, estrategia de producto, desarrollo de software y relacionamiento con proveedores.', education:'Ingeniero Industrial e Ingeniero de Sistemas y Computación, Universidad de los Andes', languages:'Español, Inglés', years_of_experience:1, certifications:[], experience:[] },
  { id:'c38', name:'David Rincón',              role_title:'Senior Consultant',                       seniority:'Senior Consultant', skills:['Digital Transformation','IT Strategy','Cloud'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c39', name:'Daniel Ángel',              role_title:'Senior Consultant',                       seniority:'Senior Consultant', skills:['Change Management','Communications','Training'], available_from:'2026-12-31', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c40', name:'Gabriela García',           role_title:'Senior Consultant',                       seniority:'Senior Consultant', skills:['Business Analysis','Process Mapping','Visio'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c41', name:'Laura Forero',              role_title:'Senior Consultant',                       seniority:'Senior Consultant', skills:['Data Analytics','Power BI','SQL'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c42', name:'Lina María Gómez',          role_title:'Consultant',                              seniority:'Consultant',        skills:['Research','Excel','PowerPoint'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c43', name:'Juan Felipe Sánchez',       role_title:'Consultant',                              seniority:'Consultant',        skills:['Business Analysis','Research','Excel'], available_from:'2026-08-21', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c44', name:'Nathalia Quiroga',          role_title:'Consultant',                              seniority:'Consultant',        skills:['Data Analytics','SQL','Python'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c45', name:'Sebastian Gomez',           role_title:'Consultant',                              seniority:'Consultant',        skills:['Process Optimization','Operations','Excel'], available_from:'2026-12-31', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c46', name:'Andrés Villota',            role_title:'Consultant',                              seniority:'Consultant',        skills:['Financial Modeling','Research','PowerPoint'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c47', name:'Juan Currea',               role_title:'Consultant',                              seniority:'Consultant',        skills:['Digital Transformation','IT','Research'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c48', name:'Julián Cardenas',           role_title:'Consultant',                              seniority:'Consultant',        skills:['Change Management','Communications','Training'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c49', name:'Emilio Baquerizo',          role_title:'Consultant',                              seniority:'Consultant',        skills:['Strategy','Research','Excel'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c50', name:'Santiago Arevalo',          role_title:'Consultant',                              seniority:'Consultant',        skills:['Data Analytics','Power BI','SQL'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c51', name:'Matias Bermudez',           role_title:'Consultant',                              seniority:'Consultant',        skills:['Business Analysis','Process Mapping','Visio'], available_from:'2026-05-29', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c52', name:'Juana Mejia',               role_title:'Consultant',                              seniority:'Consultant',        skills:['Organizational Design','HR','Research'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c53', name:'Sophie Tobias',             role_title:'Consultant',                              seniority:'Consultant',        skills:['Project Management','Agile','Communications'], available_from:'2026-12-31', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c54', name:'Manuela Lizcano',           role_title:'Consultant',                              seniority:'Consultant',        skills:['Financial Modeling','Research','Excel'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c55', name:'Giuliana Volpi',            role_title:'Consultor',                               seniority:'Consultant',        skills:['Data Analytics','Machine Learning','Advanced Analytics','Python','Data Architecture'], available_from:'2026-05-29', bio:'Giuliana cuenta con experiencia como Data Analyst y ejecución de proyectos de analítica avanzada, machine learning y arquitectura de soluciones.', education:null, languages:'Español, Inglés, Italiano', years_of_experience:null, certifications:[], experience:[] },
  { id:'c56', name:'Juan Felipe Puig',          role_title:'Consultant',                              seniority:'Consultant',        skills:['Digital Transformation','IT','Agile'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c57', name:'Juan Manuel Perez',         role_title:'Intern',                                  seniority:'Intern',            skills:['Research','Excel','PowerPoint'], available_from:'2026-11-30', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c58', name:'Maria Fernanda Amador',     role_title:'Intern',                                  seniority:'Intern',            skills:['Research','Excel','Data Analytics'], available_from:'2026-06-12', bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c59', name:'Amalia Carbonell',          role_title:'Intern',                                  seniority:'Intern',            skills:['Research','PowerPoint','Communications'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
  { id:'c60', name:'Santiago Celis',            role_title:'Practicante de Consultoría en TI',        seniority:'Intern',            skills:['AI/GenAI','Platform Development','Data Analysis','UX','Systems Engineering'], available_from:null, bio:'Santiago cuenta con experiencia en desarrollo y soporte de plataformas tecnológicas, con foco en mejora de la experiencia del usuario y soluciones basadas en IA generativa.', education:'Ingeniería de Sistemas y Computación, Universidad de los Andes', languages:'Español, Inglés', years_of_experience:null, certifications:[], experience:[] },
  { id:'c61', name:'Sofia Correa',              role_title:'Intern',                                  seniority:'Intern',            skills:['Research','Excel','PowerPoint'], available_from:null, bio:null, education:null, languages:null, years_of_experience:null, certifications:[], experience:[] },
]

function nameToEmail(name) {
  const parts = name.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').split(' ').filter(Boolean)
  return `${parts[0]}.${parts[parts.length - 1]}@bip-group.com`
}

function escape(s) {
  if (s === null || s === undefined) return 'NULL'
  return `'${String(s).replace(/'/g, "''")}'`
}

function arr(a) {
  if (!a || a.length === 0) return "ARRAY[]::text[]"
  return `ARRAY[${a.map(s => `'${String(s).replace(/'/g, "''")}'`).join(',')}]`
}

let sql = `-- Schema changes: add CV columns and remove auth FK\n`
sql += `ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;\n`
sql += `ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email text UNIQUE;\n`
sql += `ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio text;\n`
sql += `ALTER TABLE profiles ADD COLUMN IF NOT EXISTS education text;\n`
sql += `ALTER TABLE profiles ADD COLUMN IF NOT EXISTS languages text;\n`
sql += `ALTER TABLE profiles ADD COLUMN IF NOT EXISTS years_of_experience integer;\n`
sql += `ALTER TABLE profiles ADD COLUMN IF NOT EXISTS certifications text[] DEFAULT '{}';\n`
sql += `ALTER TABLE profiles ADD COLUMN IF NOT EXISTS experience jsonb DEFAULT '[]';\n\n`
sql += `-- Bulk insert all consultants\n`
sql += `INSERT INTO profiles (id, email, name, role_title, seniority, skills, available_from, bio, education, languages, years_of_experience, certifications, experience, user_role, is_active)\nVALUES\n`

const rows = consultants.map(c => {
  const email = nameToEmail(c.name)
  const id = `gen_random_uuid()`
  const avail = c.available_from ? `'${c.available_from}'` : 'NULL'
  const exp = c.experience && c.experience.length > 0 ? `'${JSON.stringify(c.experience).replace(/'/g, "''")}'::jsonb` : "'[]'::jsonb"
  return `  (${id}, '${email}', ${escape(c.name)}, ${escape(c.role_title)}, '${c.seniority}', ${arr(c.skills)}, ${avail}, ${escape(c.bio)}, ${escape(c.education)}, ${escape(c.languages)}, ${c.years_of_experience ?? 'NULL'}, ${arr(c.certifications)}, ${exp}, 'consultant', true)`
})

sql += rows.join(',\n') + '\nON CONFLICT (email) DO NOTHING;\n\n'

sql += `-- Update sign-up policy to also allow update (for linking auth accounts)\n`
sql += `DROP POLICY IF EXISTS "consultant creates own profile" ON profiles;\n`
sql += `CREATE POLICY "consultant creates own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id OR email = (SELECT email FROM auth.users WHERE id = auth.uid()));\n`
sql += `CREATE POLICY "consultant links own profile" ON profiles FOR UPDATE USING (email = (SELECT email FROM auth.users WHERE id = auth.uid()));\n`

console.log(sql)
