-- Schema changes: add CV columns and remove auth FK
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email text UNIQUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS education text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS languages text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS years_of_experience integer;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS certifications text[] DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS experience jsonb DEFAULT '[]';

-- Bulk insert all consultants
INSERT INTO profiles (id, email, name, role_title, seniority, skills, available_from, bio, education, languages, years_of_experience, certifications, experience, user_role, is_active)
VALUES
  (gen_random_uuid(), 'hernando.baquero@bip-group.com', 'Hernando Baquero', 'Senior Partner', 'Senior Partner', ARRAY['Digital Transformation','Operational Excellence','IT Strategy','Strategic Planning','Business Intelligence','Post-merger Integration'], '2026-12-31', 'Hernando tiene más de 20 años de experiencia en transformación digital, excelencia operativa, planificación estratégica de negocios y TI y gestión de proyectos complejos. Antes de fundar Advantis en 2003, fue consultor en Booz Allen Hamilton y Gerente de una empresa de consultoría colombiana.', 'Ingeniero Industrial, Universidad de los Andes · MBA, INSEAD', 'Español, Inglés', 20, ARRAY[]::text[], '[{"id":"e1a","title":"Transformación Digital y Tecnologías de la Información","client":"Sector Financiero, LATAM","period":"2003 – presente","description":"Soporte en Transformación Digital — mejora de la experiencia del cliente, modernización de aplicaciones heredadas y excelencia operativa."},{"id":"e1b","title":"Transformación Organizacional","client":"Banca y Sector Real","period":"2003 – presente","description":"Integración post-fusión de bancos, fondos de pensiones y empresas de consumo con énfasis en TI."}]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'john.romero@bip-group.com', 'John Jairo Romero', 'Partner', 'Partner', ARRAY['Digital Transformation','IT Strategy','Cybersecurity','M&A','Financial Services','Process Improvement'], '2026-12-31', 'John Jairo ha dedicado su carrera de más de 27 años en consultoría a ayudar a empresas en múltiples industrias a transformar su negocio mediante tecnología e innovación digital.', 'Ingeniero de Sistemas, Universidad de Los Andes', 'Español, Inglés', 27, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.forero@bip-group.com', 'Juan Fernando Forero', 'Partner', 'Partner', ARRAY['IT Planning','IT Management','Systems Architecture','Project Management','Software Selection','Integration'], '2026-08-21', 'Juan Fernando cuenta con más de 30 años de experiencia en consultoría gerencial para resolver asuntos estratégicos de TI.', 'Ingeniero de Sistemas y Computación, Universidad de Los Andes', 'Español, Inglés', 30, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'henry.jaimes@bip-group.com', 'Henry Jaimes', 'Director', 'Director', ARRAY['IT Strategy','IT Architecture','Digital Transformation','Organizational Design','Agile','Due Diligence'], '2026-11-30', 'Henry tiene una amplia experiencia en consultoría en estrategia de tecnología y negocios, arquitectura de TI, implementación de estrategias de transformación digital.', 'Ingeniero de Sistemas, Universidad de Los Andes · Magíster en Tecnologías de la Información para el Negocio', 'Español, Inglés', NULL, ARRAY['Scrum Master Certificado'], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'andres.cubillos@bip-group.com', 'Andrés Cubillos', 'Senior Manager', 'Senior Manager', ARRAY['Operational Excellence','IT Strategy','Enterprise Architecture','Agile','Software Implementation','Process Optimization'], '2026-05-29', 'Andrés tiene más de 12 años de experiencia enfocándose en dirección de proyectos complejos, planeación de TI, modelos de gestión y transformación de modelos operativos.', 'Ingeniero, Universidad de Los Andes', NULL, 12, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'jaime.barco@bip-group.com', 'Jaime Barco', 'Experto Datos y Analítica', 'Senior Manager', ARRAY['Data Analytics','Data Mining','Business Intelligence','AI/ML','Data Quality','Data Strategy'], '2026-12-31', 'Jaime ha participado en más de 80 proyectos relacionados con Data y Analítica. Especialista en técnicas de minería de datos, calidad de datos e implantación de sistemas de inteligencia artificial.', 'Ingeniero de Sistemas, Universidad Autónoma de Manizales · Especialización en Desarrollo Gerencial · PDD, INALDE', 'Español, Portugués', 20, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'carla.villaverde@bip-group.com', 'Carla Villaverde', 'Directora Talento Humano', 'Senior Manager', ARRAY['HR Strategy','Talent Acquisition','Organizational Design','Employer Branding','Engagement Strategy','Change Management'], '2026-07-31', 'Carla cuenta con más de 15 años de experiencia en talento humano, trabajando en la definición e implementación de estrategias que apalanquen los objetivos del negocio.', NULL, 'Español, Inglés', 15, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'felipe.estrada@bip-group.com', 'Felipe Estrada', 'Senior Manager', 'Senior Manager', ARRAY['Digital Transformation','IT Strategy','Data Strategy','IT Architecture','Business Strategy'], '2026-12-31', 'Felipe tiene 10+ años de experiencia. Anteriormente trabajó en IBM Colombia como consultor de TI.', 'Ingeniero en Sistemas e Informática, Universidad de los Andes', 'Español, Inglés', 10, ARRAY['Scrum Master Certificado'], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'ivan.melo@bip-group.com', 'Iván Melo', 'Gerente Senior – Especialista Arquitectura TI', 'Senior Manager', ARRAY['IT Architecture','Enterprise Architecture','Digital Transformation','IT Strategy','Software Selection','Financial Services'], '2026-08-21', 'Iván Mauricio tiene 15+ años de experiencia en proyectos de arquitectura empresarial y asuntos estratégicos de TI.', 'Máster en Ingeniería e Ingeniero de Sistemas y Computación, Universidad de Los Andes', 'Español, Inglés', 15, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'magda.patino@bip-group.com', 'Magda Patiño', 'Especialista en Gestión de Proyectos', 'Manager', ARRAY['Project Management','Software Implementation','Change Management','QA','ERP'], '2026-08-21', 'Magda es Especialista de Gestión de Proyectos con más de 25 años de experiencia en implementación de soluciones informáticas.', 'Ingeniera de Sistemas, Universidad de Los Andes', NULL, 25, ARRAY['Scrum Master Certificada'], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'alejandro.manrique@bip-group.com', 'Alejandro Manrique', 'Manager', 'Manager', ARRAY['Strategy','Business Analysis','Financial Modeling'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'john.casallas@bip-group.com', 'John Casallas', 'Manager', 'Manager', ARRAY['Project Management','Software Implementation','IT Strategy','Enterprise Architecture','Digital Transformation','Business Process Automation'], '2026-11-30', 'John cuenta con 13+ años de experiencia. Sus principales áreas de especialización son gestión de proyectos de implementación de software y arquitectura empresarial.', 'Ingeniero de Sistemas, Universidad de Los Andes · Magíster en Ingeniería de Sistemas', NULL, 13, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'felipe.mediorreal@bip-group.com', 'Felipe Mediorreal', 'Manager', 'Manager', ARRAY['Operations','Supply Chain','Process Optimization'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'santiago.serna@bip-group.com', 'Santiago Serna', 'Manager', 'Manager', ARRAY['Business Strategy','Digital Transformation','Operational Excellence','Agile Transformation'], '2026-12-31', 'Santiago Serna cuenta con más de 8 años de experiencia en proyectos de estrategia de negocios, transformación digital, gestión de tecnología y excelencia operacional.', 'MBA, Duke University · Ingeniero Industrial y Civil, Universidad de Los Andes', 'Español, Inglés', 8, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'angelica.tarazona@bip-group.com', 'Angélica Tarazona', 'Manager', 'Manager', ARRAY['HR','Finance','Organizational Design','Change Management','Talent Management'], '2026-08-21', NULL, 'Magíster en Finanzas, Universidad de Los Andes · Administradora y Economista, Universidad Metropolitana (Caracas)', NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'andrea.rosales@bip-group.com', 'Andrea Rosales', 'Senior Associate', 'Senior Associate', ARRAY['Business Analysis','Process Optimization','Excel'], '2026-12-31', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'guillermo.ferro@bip-group.com', 'Guillermo Ferro', 'Asociado Senior', 'Senior Associate', ARRAY['IT Strategy','IT Architecture','Digital Transformation','Enterprise Architecture'], '2026-11-30', NULL, 'Magíster en Arquitectura de TI, Universidad de los Andes', NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'diego.castro@bip-group.com', 'Diego Castro', 'Asociado', 'Senior Associate', ARRAY['IT Strategy','Digital Transformation','Agile','Lean Digital','Organizational Strategy'], NULL, 'Diego Castro cuenta con 4 años de experiencia en proyectos de estrategia de tecnología y negocio, estrategia organizacional, implementación de metodologías ágiles y lean digital.', NULL, 'Español, Inglés', 4, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'raul.aular@bip-group.com', 'Raúl Aular', 'Asociado', 'Associate', ARRAY['IT Management','Strategic Planning','Process Management','ERP','Turnaround','Retail'], '2026-11-30', 'Raúl cuenta con experiencia en implementación de modelos de gestión de TI, rediseño e implementación de procesos y planes de turnaround.', NULL, 'Español, Inglés, Portugués', NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'lina.gutierrez@bip-group.com', 'Lina Gutiérrez', 'Senior Associate', 'Senior Associate', ARRAY['Change Management','Training','Communications'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.figueroa@bip-group.com', 'Juan David Figueroa', 'Asociado Sr', 'Senior Associate', ARRAY['Business Strategy','Digital Transformation','Process Optimization','Operating Model Design','Financial Efficiency'], '2026-05-29', 'Juan David cuenta con más de 6 años de experiencia en estrategia de negocio y tecnología, transformación digital y optimización de procesos.', 'Economista, Pontificia Universidad Javeriana', 'Español, Inglés', 6, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'antonio.perez@bip-group.com', 'Antonio Pérez', 'Asociado', 'Associate', ARRAY['Digital Transformation','ERP','CRM','IT Strategy','Energy','Carve-out'], '2026-12-31', 'Antonio tiene más de 6 años de experiencia en consultoría estratégica y de operaciones en los sectores de energía, utilities y servicios financieros.', NULL, 'Español (nativo), Inglés C1', 6, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'santiago.restrepo@bip-group.com', 'Santiago Restrepo', 'Consultor Senior', 'Associate', ARRAY['Digital Transformation','Software Implementation','IT Strategy','Operational Excellence','Strategic Planning'], '2026-11-30', 'Santiago cuenta con 3 años de experiencia en proyectos de transformación digital, implementación de software, definición de estrategia de tecnología y excelencia operacional.', 'Ingeniero de Sistemas e Ingeniero Industrial, Universidad de los Andes', 'Español, Inglés', 3, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'ixtli.barbosa@bip-group.com', 'Ixtli Yolot Barbosa', 'Consultor Senior', 'Associate', ARRAY['Agile','Digital Strategy','Lean','ERP','IT Strategy','Scrum Master'], '2026-05-29', 'Ixtli cuenta con experiencia en implementaciones Agile, desarrollo de planes estratégicos de TI y negocio.', 'Ingeniería de Sistemas, Universidad de Los Andes', NULL, 2, ARRAY['Scrum Master Certificada'], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.yara@bip-group.com', 'Juan David Yara', 'Associate', 'Associate', ARRAY['Strategy','Research','PowerPoint'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'violeta.rodriguez@bip-group.com', 'Violeta Rodríguez', 'Asociada', 'Associate', ARRAY['Digital Transformation','IT Architecture','Software Selection','Gap Analysis','Technology Strategy'], NULL, 'Violeta cuenta con más de 3 años de experiencia en proyectos de transformación digital, definición de arquitectura, procesos de selección de soluciones tecnológicas.', NULL, 'Español, Inglés', 3, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'maria.gonzalez@bip-group.com', 'Maria Camila González', 'Consultor Senior', 'Senior Consultant', ARRAY['Strategy','Financial Services','Telecoms','Oil & Gas','Business Analysis'], NULL, 'María Camila cuenta con 5+ años de experiencia en industria y en consultoría estratégica en los sectores financiero, oil & gas y telecomunicaciones.', NULL, 'Español, Inglés, Francés', NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'maria.coronado@bip-group.com', 'Maria Camila Coronado', 'Consultor Senior', 'Senior Consultant', ARRAY['Operating Model Design','Process Improvement','Lean Six Sigma','Design Thinking','Operational Excellence'], '2026-08-21', 'María Camila cuenta con más de 5 años de experiencia en la transformación de modelos operativos y mejora de procesos.', NULL, NULL, 5, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'maria.lima@bip-group.com', 'Maria Carolina De Lima', 'Consultor Senior - HRBP', 'Senior Consultant', ARRAY['Change Management','HR','Organizational Design','Training','Talent Management','Internal Communications'], '2026-07-31', 'María Carolina cuenta con más de 4 años de experiencia en equipos y procesos de talento humano.', 'Administradora de Empresas, Pontificia Universidad Javeriana', 'Español, Inglés', 4, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'nathalia.velez@bip-group.com', 'Nathalia Vélez', 'Consultor Senior', 'Senior Consultant', ARRAY['IT Strategy','Operational Excellence','Digital Transformation','Workforce Evolution','Strategic Planning'], '2026-11-30', 'Nathalia tiene más de 3 años de experiencia en planeación de estrategias de tecnología, excelencia operacional y programas de transformación operativa.', 'Administradora de Empresas con énfasis en Innovación con Tecnología, Universidad de los Andes', 'Español', 3, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.alarcon@bip-group.com', 'Juan David Alarcón', 'Consultor Senior', 'Senior Consultant', ARRAY['Web Development','Financial Modeling','Cloud (Azure/AWS)','Digital Transformation'], NULL, 'Juan David cuenta con experiencia en diseño e implementación de páginas web y desarrollo de modelos financieros.', 'Ingeniero Biomédico e Ingeniero Mecánico, Universidad de los Andes', 'Español, Inglés', NULL, ARRAY['Certificado Azure','Certificado AWS'], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'maria.crissien@bip-group.com', 'María Crissien', 'Consultor Senior', 'Senior Consultant', ARRAY['Strategic Planning','Digital Transformation','Due Diligence','SAP S4/HANA','ERP','Oil & Gas'], '2026-11-30', 'Maria Alejandra cuenta con experiencia en planeación estratégica, transformación digital, due diligence y gestión e implementación de proyectos de tecnología.', NULL, 'Español, Inglés', 1, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'fabian.becerra@bip-group.com', 'Fabian Becerra', 'Consultor Senior de Tecnología', 'Senior Consultant', ARRAY['Data Analytics','Risk Management','Financial Technology','Business Intelligence','AI','Data Engineering','Automation'], '2026-05-29', 'Fabian es Technology Consultant con experiencia en proyectos de analítica, riesgo y transformación tecnológica en el sector financiero.', NULL, NULL, 3, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'nicolas.velez@bip-group.com', 'Nicolas Velez', 'Senior Consultant', 'Senior Consultant', ARRAY['Software Implementation','IT','Financial Consulting','PMO','Digital Transformation'], '2026-08-21', 'Nicolás tiene 4+ años de experiencia en consultoría y la industria financiera. Ha liderado proyectos cross-country para grandes corporaciones.', 'Ingeniero Industrial, Universidad de Los Andes · Minor en Matemáticas', 'Español, Inglés', 4, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'mateo.pimentel@bip-group.com', 'Mateo Pimentel', 'Senior Consultant', 'Senior Consultant', ARRAY['Process Optimization','LEAN','Operations'], '2026-08-21', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'diego.campos@bip-group.com', 'Diego Campos', 'Consultor Senior', 'Senior Consultant', ARRAY['Operating Model Design','Software Selection','IT Planning','Lean Six Sigma','Post-merger Integration'], '2026-11-30', 'Diego cuenta con experiencia en planeación y ejecución de proyectos de diseño de modelos operativos post-integración.', 'Administrador de Empresas y Especialista en Inteligencia de Mercados, Universidad de los Andes', 'Español, Inglés', NULL, ARRAY['Lean Six Sigma Yellow Belt'], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.patino@bip-group.com', 'Juan Felipe Patiño', 'Consultor', 'Senior Consultant', ARRAY['Product Strategy','Software Development','IT Consulting','Product Management','Vendor Management'], '2026-11-30', 'Juan Felipe cuenta con experiencia en desarrollo de productos, estrategia de producto, desarrollo de software y relacionamiento con proveedores.', 'Ingeniero Industrial e Ingeniero de Sistemas y Computación, Universidad de los Andes', 'Español, Inglés', 1, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'david.rincon@bip-group.com', 'David Rincón', 'Senior Consultant', 'Senior Consultant', ARRAY['Digital Transformation','IT Strategy','Cloud'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'daniel.angel@bip-group.com', 'Daniel Ángel', 'Senior Consultant', 'Senior Consultant', ARRAY['Change Management','Communications','Training'], '2026-12-31', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'gabriela.garcia@bip-group.com', 'Gabriela García', 'Senior Consultant', 'Senior Consultant', ARRAY['Business Analysis','Process Mapping','Visio'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'laura.forero@bip-group.com', 'Laura Forero', 'Senior Consultant', 'Senior Consultant', ARRAY['Data Analytics','Power BI','SQL'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'lina.gomez@bip-group.com', 'Lina María Gómez', 'Consultant', 'Consultant', ARRAY['Research','Excel','PowerPoint'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.sanchez@bip-group.com', 'Juan Felipe Sánchez', 'Consultant', 'Consultant', ARRAY['Business Analysis','Research','Excel'], '2026-08-21', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'nathalia.quiroga@bip-group.com', 'Nathalia Quiroga', 'Consultant', 'Consultant', ARRAY['Data Analytics','SQL','Python'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'sebastian.gomez@bip-group.com', 'Sebastian Gomez', 'Consultant', 'Consultant', ARRAY['Process Optimization','Operations','Excel'], '2026-12-31', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'andres.villota@bip-group.com', 'Andrés Villota', 'Consultant', 'Consultant', ARRAY['Financial Modeling','Research','PowerPoint'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.currea@bip-group.com', 'Juan Currea', 'Consultant', 'Consultant', ARRAY['Digital Transformation','IT','Research'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'julian.cardenas@bip-group.com', 'Julián Cardenas', 'Consultant', 'Consultant', ARRAY['Change Management','Communications','Training'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'emilio.baquerizo@bip-group.com', 'Emilio Baquerizo', 'Consultant', 'Consultant', ARRAY['Strategy','Research','Excel'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'santiago.arevalo@bip-group.com', 'Santiago Arevalo', 'Consultant', 'Consultant', ARRAY['Data Analytics','Power BI','SQL'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'matias.bermudez@bip-group.com', 'Matias Bermudez', 'Consultant', 'Consultant', ARRAY['Business Analysis','Process Mapping','Visio'], '2026-05-29', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juana.mejia@bip-group.com', 'Juana Mejia', 'Consultant', 'Consultant', ARRAY['Organizational Design','HR','Research'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'sophie.tobias@bip-group.com', 'Sophie Tobias', 'Consultant', 'Consultant', ARRAY['Project Management','Agile','Communications'], '2026-12-31', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'manuela.lizcano@bip-group.com', 'Manuela Lizcano', 'Consultant', 'Consultant', ARRAY['Financial Modeling','Research','Excel'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'giuliana.volpi@bip-group.com', 'Giuliana Volpi', 'Consultor', 'Consultant', ARRAY['Data Analytics','Machine Learning','Advanced Analytics','Python','Data Architecture'], '2026-05-29', 'Giuliana cuenta con experiencia como Data Analyst y ejecución de proyectos de analítica avanzada, machine learning y arquitectura de soluciones.', NULL, 'Español, Inglés, Italiano', NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.puig@bip-group.com', 'Juan Felipe Puig', 'Consultant', 'Consultant', ARRAY['Digital Transformation','IT','Agile'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'juan.perez@bip-group.com', 'Juan Manuel Perez', 'Intern', 'Intern', ARRAY['Research','Excel','PowerPoint'], '2026-11-30', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'maria.amador@bip-group.com', 'Maria Fernanda Amador', 'Intern', 'Intern', ARRAY['Research','Excel','Data Analytics'], '2026-06-12', NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'amalia.carbonell@bip-group.com', 'Amalia Carbonell', 'Intern', 'Intern', ARRAY['Research','PowerPoint','Communications'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'santiago.celis@bip-group.com', 'Santiago Celis', 'Practicante de Consultoría en TI', 'Intern', ARRAY['AI/GenAI','Platform Development','Data Analysis','UX','Systems Engineering'], NULL, 'Santiago cuenta con experiencia en desarrollo y soporte de plataformas tecnológicas, con foco en mejora de la experiencia del usuario y soluciones basadas en IA generativa.', 'Ingeniería de Sistemas y Computación, Universidad de los Andes', 'Español, Inglés', NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true),
  (gen_random_uuid(), 'sofia.correa@bip-group.com', 'Sofia Correa', 'Intern', 'Intern', ARRAY['Research','Excel','PowerPoint'], NULL, NULL, NULL, NULL, NULL, ARRAY[]::text[], '[]'::jsonb, 'consultant', true)
ON CONFLICT (email) DO NOTHING;

-- Update sign-up policy to also allow update (for linking auth accounts)
DROP POLICY IF EXISTS "consultant creates own profile" ON profiles;
CREATE POLICY "consultant creates own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id OR email = (SELECT email FROM auth.users WHERE id = auth.uid()));
CREATE POLICY "consultant links own profile" ON profiles FOR UPDATE USING (email = (SELECT email FROM auth.users WHERE id = auth.uid()));

